# Generated by Django 3.2.7 on 2021-10-23 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basename', models.CharField(max_length=100)),
                ('withCurrency', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('tc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WxPortfolio.transactioncurrency')),
            ],
        ),
    ]
